from pizzactrl import fs_names
from pizzactrl.storyboard import *

REC_NAME = fs_names.RecFile('name.wav')
REC_WARMUP = fs_names.RecFile('warmup.wav')
PROFILE_PIC = fs_names.RecFile('profile.jpg')
REC_CITY = fs_names.RecFile('cityname.wav')
REC_CITY_DESC = fs_names.RecFile('city-desc.wav')
REC_CITY_SOUND = fs_names.RecFile('city-sound.wav')
REC_CITY_VIDEO = fs_names.RecFile('city.h264')


STORYBOARD = Storyboard(
    Chapter(    # Start position
        Do(Activity.ADVANCE_LEFT,
            steps=-1,
            speed=4),  # HOR01
        Do(Activity.ADVANCE_LEFT),  # HOR01
        Do(Activity.ADVANCE_UP,
            steps=-1,
            speed=3),
        Do(Activity.ADVANCE_UP)     # VERT01
    ),
    Chapter(    # X1 = 0
        Do(Activity.LIGHT_FRONT,
                w=1.0,
                fade=1.5),
        Do(Activity.PLAY_SOUND,
            DE=fs_names.StoryFile('DE01'),
            EN=fs_names.StoryFile('EN01'),
            TR=fs_names.StoryFile('TR01')),
        Do(Activity.WAIT_FOR_INPUT,
            on_yellow=Select(Option.CONTINUE),
            DE=fs_names.StoryFile('DE02'),
            EN=fs_names.StoryFile('EN02'),
            TR=fs_names.StoryFile('TR02')),
    ),
    Chapter(    # X2
        Do(Activity.ADVANCE_UP),        # VERT02
        Do(Activity.PLAY_SOUND,
            DE=fs_names.StoryFile('DE03'),
            EN=fs_names.StoryFile('EN03'),
            TR=fs_names.StoryFile('TR03')),
        Do(Activity.ADVANCE_UP),        # VERT03
        Do(Activity.PLAY_SOUND,
            DE=fs_names.StoryFile('DE04'),
            EN=fs_names.StoryFile('EN04'),
            TR=fs_names.StoryFile('TR04')),
        Do(Activity.PARALLEL,
        activities=[
            Do(Activity.LIGHT_FRONT,
                fade=1.5),
            Do(Activity.LIGHT_BACK,     # HOR01
                w=1.0,
                fade=1.5)
        ]),
        Do(Activity.PLAY_SOUND,
            DE=fs_names.StoryFile('DE05'),
            EN=fs_names.StoryFile('EN05'),
            TR=fs_names.StoryFile('TR05')),
        Do(Activity.ADVANCE_UP),        # VERT04
        Do(Activity.PLAY_SOUND,
            DE=fs_names.StoryFile('DE06'),
            EN=fs_names.StoryFile('EN06'),
            TR=fs_names.StoryFile('TR06')),
        Do(Activity.LIGHT_BACK,         # Black
            fade=1.5),
        Do(Activity.WAIT_FOR_INPUT,
            on_blue=Select(Option.CONTINUE),
            DE=fs_names.StoryFile('DE07'),
            EN=fs_names.StoryFile('EN07'),
            TR=fs_names.StoryFile('TR07'))
    ),
    Chapter(    # X3
        Do(Activity.PARALLEL,
        activities=[
            Do(Activity.LIGHT_FRONT,
                w=1.0,
                fade=1.5),
            Do(Activity.ADVANCE_UP)     # VERT05
        ]),
        Do(Activity.PLAY_SOUND,
            DE=fs_names.StoryFile('DE08'),
            EN=fs_names.StoryFile('EN08'),
            TR=fs_names.StoryFile('TR08')),
        Do(Activity.PARALLEL,
        activities=[
            Do(Activity.LIGHT_FRONT,
                fade=1.5),
            Do(Activity.LIGHT_BACK,
                w=1.0,
                fade=1.5),
            Do(Activity.ADVANCE_LEFT)     # HOR02
        ]),
        Do(Activity.PLAY_SOUND,
            DE=fs_names.StoryFile('DE09'),
            EN=fs_names.StoryFile('EN09'),
            TR=fs_names.StoryFile('TR09')),
        Do(Activity.PLAY_SOUND,
            sound=fs_names.SFX_REC_AUDIO),
        Do(Activity.PLAY_SOUND,
            DE=fs_names.StoryFile('DE10'),
            EN=fs_names.StoryFile('EN10'),
            TR=fs_names.StoryFile('TR10')),
        Do(Activity.WAIT_FOR_INPUT,
            on_red=Select(Option.CONTINUE),
            DE=fs_names.StoryFile('DE11'),
            EN=fs_names.StoryFile('EN11'),
            TR=fs_names.StoryFile('TR11')),
        Do(Activity.PLAY_SOUND,
            sound=fs_names.SFX_REC_AUDIO),
        Do(Activity.RECORD_SOUND,
            duration=5.0,
            cache=True,
            filename=REC_NAME),
        Do(Activity.PLAY_SOUND,
            sound=fs_names.SFX_STOP_REC),
        Do(Activity.LIGHT_BACK,           # Black
            fade=1.5)
    ),
    Chapter(    # X4
        Do(Activity.ADVANCE_LEFT),        # HOR03
        Do(Activity.PLAY_SOUND,
            DE=fs_names.StoryFile('DE12'),
            EN=fs_names.StoryFile('EN12'),
            TR=fs_names.StoryFile('TR12')),
        Do(Activity.PLAY_SOUND,
            sound=REC_NAME),
        Do(Activity.PLAY_SOUND,
            DE=fs_names.StoryFile('DE13'),
            EN=fs_names.StoryFile('EN13'),
            TR=fs_names.StoryFile('TR13')),
        Do(Activity.LIGHT_BACK,
            w=1.0,
            fade=1.5),
        Do(Activity.PLAY_SOUND,
            DE=fs_names.StoryFile('DE14'),
            EN=fs_names.StoryFile('EN14'),
            TR=fs_names.StoryFile('TR14')),
        Do(Activity.WAIT_FOR_INPUT,
            on_green=Select(Option.CONTINUE),
            DE=fs_names.StoryFile('DE15'),
            EN=fs_names.StoryFile('EN15'),
            TR=fs_names.StoryFile('TR15')),
        Do(Activity.PLAY_SOUND,
            sound=fs_names.SFX_REC_AUDIO),
        Do(Activity.RECORD_SOUND,
            duration=60.0,
            filename=REC_WARMUP),
        Do(Activity.PLAY_SOUND,
            sound=fs_names.SFX_STOP_REC),
        Do(Activity.LIGHT_BACK,
            fade=1.5),
    ),
    Chapter(    # X5
        Do(Activity.PARALLEL,
        activities=[
            Do(Activity.LIGHT_FRONT,
                w=1.0,
                fade=1.5),
            Do(Activity.ADVANCE_UP)       # VERT06
        ]),
        Do(Activity.PLAY_SOUND,
            DE=fs_names.StoryFile('DE16'),
            EN=fs_names.StoryFile('EN16'),
            TR=fs_names.StoryFile('TR16')),
        Do(Activity.LIGHT_FRONT,          # Black
            fade=1.5),
        Do(Activity.WAIT_FOR_INPUT,
            on_yellow=Select(Option.CONTINUE)),
        Do(Activity.PLAY_SOUND,
            sound=fs_names.SFX_REC_AUDIO),
        Do(Activity.TAKE_PHOTO,
            filename=PROFILE_PIC),
        Do(Activity.PLAY_SOUND,
            sound=fs_names.SFX_SHUTTER)
    ),
    Chapter(    # X6
        Do(Activity.PLAY_SOUND,
            DE=fs_names.StoryFile('DE17'),
            EN=fs_names.StoryFile('EN17'),
            TR=fs_names.StoryFile('TR17')),
        Do(Activity.WAIT_FOR_INPUT,
            on_blue=Select(Option.CONTINUE))
    ),
    Chapter(    # X7
        Do(Activity.PLAY_SOUND,
            DE=fs_names.StoryFile('DE18'),
            EN=fs_names.StoryFile('EN18'),
            TR=fs_names.StoryFile('TR18')),
        Do(Activity.PARALLEL,
        activities=[
            Do(Activity.LIGHT_FRONT,
                w=1.0,
                fade=1.5),
            Do(Activity.ADVANCE_UP)     # VERT07
        ]),
        Do(Activity.PLAY_SOUND,
            DE=fs_names.StoryFile('DE19'),
            EN=fs_names.StoryFile('EN19'),
            TR=fs_names.StoryFile('TR19')),
        Do(Activity.PARALLEL,
        activities=[
            Do(Activity.LIGHT_FRONT,
                fade=1.5),
            Do(Activity.LIGHT_BACK,
                w=1.0,
                fade=1.5),
            Do(Activity.ADVANCE_LEFT)     # HOR04
        ]),
        Do(Activity.PLAY_SOUND,
            DE=fs_names.StoryFile('DE20'),
            EN=fs_names.StoryFile('EN20'),
            TR=fs_names.StoryFile('TR20')),
        Do(Activity.PARALLEL,
        activities=[
            Do(Activity.LIGHT_FRONT,
                fade=1.5),
            Do(Activity.LIGHT_BACK,
                fade=1.5)                 # Black
        ]),
        Do(Activity.WAIT_FOR_INPUT,
            on_red=Select(Option.CONTINUE),
            DE=fs_names.StoryFile('DE21'),
            EN=fs_names.StoryFile('EN21'),
            TR=fs_names.StoryFile('TR21')),
    ),
    Chapter(    # X8
        Do(Activity.PARALLEL,
        activities=[
            Do(Activity.LIGHT_FRONT,
                w=1.0,
                fade=1.5),
            Do(Activity.ADVANCE_UP)       # VERT08
        ]),
        Do(Activity.PLAY_SOUND,
            DE=fs_names.StoryFile('DE22'),
            EN=fs_names.StoryFile('EN22'),
            TR=fs_names.StoryFile('TR22')),
        Do(Activity.PARALLEL,
        activities=[
            Do(Activity.LIGHT_FRONT,
                fade=1.5),
            Do(Activity.LIGHT_BACK,
                w=1.0,
                fade=1.5),
            Do(Activity.ADVANCE_LEFT)     # HOR05
        ]),
        Do(Activity.PLAY_SOUND,
            DE=fs_names.StoryFile('DE23'),
            EN=fs_names.StoryFile('EN23'),
            TR=fs_names.StoryFile('TR23')),
        Do(Activity.LIGHT_BACK,           # Black
            fade=1.5),
        Do(Activity.WAIT_FOR_INPUT,
            on_green=Select(Option.CONTINUE),
            DE=fs_names.StoryFile('DE24'),
            EN=fs_names.StoryFile('EN24'),
            TR=fs_names.StoryFile('TR24')),
    ),
    Chapter(    # X9
        Do(Activity.PARALLEL,
        activities=[
            Do(Activity.LIGHT_FRONT,
                w=1.0,
                fade=1.5),
            Do(Activity.ADVANCE_UP)       # VERT09
        ]),
        Do(Activity.PLAY_SOUND,
            DE=fs_names.StoryFile('DE25'),
            EN=fs_names.StoryFile('EN25'),
            TR=fs_names.StoryFile('TR25')),
        Do(Activity.PARALLEL,
        activities=[
            Do(Activity.LIGHT_FRONT,
                fade=1.5),
            Do(Activity.LIGHT_BACK,
                w=1.0,
                fade=1.5),
            Do(Activity.ADVANCE_LEFT)     # HOR06
        ]),
        Do(Activity.PLAY_SOUND,
            DE=fs_names.StoryFile('DE26'),
            EN=fs_names.StoryFile('EN26'),
            TR=fs_names.StoryFile('TR26')),
        Do(Activity.LIGHT_BACK,           # Black
            fade=1.5),
        Do(Activity.WAIT_FOR_INPUT,
            on_yellow=Select(Option.CONTINUE),
            DE=fs_names.StoryFile('DE27'),
            EN=fs_names.StoryFile('EN27'),
            TR=fs_names.StoryFile('TR27')),
    ),
    Chapter(    # X10
        Do(Activity.PARALLEL,
        activities=[
            Do(Activity.LIGHT_FRONT,
                w=1.0,
                fade=1.5),
            Do(Activity.ADVANCE_UP)       # VERT10
        ]),
        Do(Activity.PLAY_SOUND,
            DE=fs_names.StoryFile('DE28'),
            EN=fs_names.StoryFile('EN28'),
            TR=fs_names.StoryFile('TR28')),
        Do(Activity.PLAY_SOUND,
            DE=fs_names.StoryFile('DE29'),
            EN=fs_names.StoryFile('EN29'),
            TR=fs_names.StoryFile('TR29')),
        Do(Activity.ADVANCE_UP),          # VERT11
        Do(Activity.PLAY_SOUND,
            DE=fs_names.StoryFile('DE30'),
            EN=fs_names.StoryFile('EN30'),
            TR=fs_names.StoryFile('TR30')),
        Do(Activity.PLAY_SOUND,
            DE=fs_names.StoryFile('DE31'),
            EN=fs_names.StoryFile('EN31'),
            TR=fs_names.StoryFile('TR31')),
        Do(Activity.WAIT_FOR_INPUT,
            on_blue=Select(Option.CONTINUE)),
        Do(Activity.PLAY_SOUND,
            sound=fs_names.SFX_REC_AUDIO),
        Do(Activity.RECORD_SOUND,
            duration=5.0,
            filename=REC_CITY),
        Do(Activity.PLAY_SOUND,
            sound=fs_names.SFX_STOP_REC),
    ),
    Chapter(    # X11
        Do(Activity.PARALLEL,
        activities=[
            Do(Activity.LIGHT_FRONT,
                fade=1.5),
            Do(Activity.LIGHT_BACK,
                w=1.0,
                fade=1.5),
            Do(Activity.ADVANCE_UP),      # VERT12
            Do(Activity.ADVANCE_LEFT),    # HOR07
        ]),
        Do(Activity.PLAY_SOUND,
            DE=fs_names.StoryFile('DE32'),
            EN=fs_names.StoryFile('EN32'),
            TR=fs_names.StoryFile('TR32')),
        Do(Activity.WAIT_FOR_INPUT,
            on_red=Select(Option.CONTINUE),
            DE=fs_names.StoryFile('DE33'),
            EN=fs_names.StoryFile('EN33'),
            TR=fs_names.StoryFile('TR33')),
        Do(Activity.PLAY_SOUND,
            sound=fs_names.SFX_REC_AUDIO),
        Do(Activity.RECORD_SOUND,
            duration=60.0,
            cache=True,
            filename=REC_CITY_DESC),
        Do(Activity.PLAY_SOUND,
            sound=fs_names.SFX_STOP_REC),
    ),
    Chapter(    # X12
        Do(Activity.ADVANCE_UP),          # VERT13
        Do(Activity.PLAY_SOUND,
            DE=fs_names.StoryFile('DE34'),
            EN=fs_names.StoryFile('EN34'),
            TR=fs_names.StoryFile('TR34')),
        Do(Activity.WAIT_FOR_INPUT,
            on_green=Select(Option.CONTINUE),
            DE=fs_names.StoryFile('DE35'),
            EN=fs_names.StoryFile('EN35'),
            TR=fs_names.StoryFile('TR35')),
        Do(Activity.PLAY_SOUND,
            sound=fs_names.SFX_REC_AUDIO),
        Do(Activity.RECORD_SOUND,
            duration=60.0,
            filename=REC_CITY_SOUND),
        Do(Activity.PLAY_SOUND,
            sound=fs_names.SFX_STOP_REC),
    ),
    Chapter(    # X13
        Do(Activity.PARALLEL,
        activities=[
            Do(Activity.LIGHT_FRONT,
                w=1.0,
                fade=1.5),
            Do(Activity.LIGHT_BACK,
                fade=1.5),
            Do(Activity.ADVANCE_UP),      # VERT14
        ]),
        Do(Activity.PLAY_SOUND,
            DE=fs_names.StoryFile('DE36'),
            EN=fs_names.StoryFile('EN36'),
            TR=fs_names.StoryFile('TR36')),
        Do(Activity.ADVANCE_UP),          # VERT15
        Do(Activity.PLAY_SOUND,
            DE=fs_names.StoryFile('DE37'),
            EN=fs_names.StoryFile('EN37'),
            TR=fs_names.StoryFile('TR37')),
        Do(Activity.WAIT_FOR_INPUT,
            on_yellow=Select(Option.CONTINUE),
            DE=fs_names.StoryFile('DE38'),
            EN=fs_names.StoryFile('EN38'),
            TR=fs_names.StoryFile('TR38')),
        Do(Activity.LIGHT_FRONT,
            fade=1.5),                    # Black
        Do(Activity.PLAY_SOUND,
            sound=fs_names.SFX_REC_AUDIO),
        Do(Activity.RECORD_VIDEO,
            duration=60.0,
            sound=REC_CITY_DESC,
            filename=REC_CITY_VIDEO),
        Do(Activity.PLAY_SOUND,
            sound=fs_names.SFX_STOP_REC),
    ),
    Chapter(    # X14
        Do(Activity.PARALLEL,
        activities=[
            Do(Activity.LIGHT_FRONT,
                w=1.0,
                fade=1.5),
            Do(Activity.ADVANCE_UP),      # VERT16
        ]),
        Do(Activity.PLAY_SOUND,
            DE=fs_names.StoryFile('DE39'),
            EN=fs_names.StoryFile('EN39'),
            TR=fs_names.StoryFile('TR39')),
        Do(Activity.PLAY_SOUND,
            sound=REC_NAME),
        Do(Activity.PLAY_SOUND,
            DE=fs_names.StoryFile('DE40'),
            EN=fs_names.StoryFile('EN40'),
            TR=fs_names.StoryFile('TR40')),
        Do(Activity.PLAY_SOUND,
            DE=fs_names.StoryFile('DE41'),
            EN=fs_names.StoryFile('EN41'),
            TR=fs_names.StoryFile('TR41')),
        Do(Activity.PLAY_SOUND,
            DE=fs_names.StoryFile('DE42'),
            EN=fs_names.StoryFile('EN42'),
            TR=fs_names.StoryFile('TR42')),
        Do(Activity.LIGHT_FRONT,
            fade=1.5)                     # Black
    )
)