from pizzactrl import storyboard, fs_names

STORYBOARD = [
    storyboard.Chapter(
        storyboard.Do(storyboard.Activity.LIGHT_LAYER,   # VERT01
                      intensity=1.0, fade=1.0)
    ),
    storyboard.Chapter(
        storyboard.Do(storyboard.Activity.PLAY_SOUND,
                      sound=fs_names.StoryFile('IC-SIBI-01')),
        storyboard.Do(storyboard.Activity.PLAY_SOUND,
                      sound=fs_names.StoryFile('IC-SIBI-02')),
        storyboard.Do(storyboard.Activity.WAIT_FOR_INPUT),
        # storyboard.Do(storyboard.Activity.ADVANCE_UP)   # VERT02up
    ),
    storyboard.Chapter(
        storyboard.Do(storyboard.Activity.PLAY_SOUND,
                      sound=fs_names.StoryFile('IC-SIBI-03')),
        # storyboard.Do(storyboard.Activity.ADVANCE_UP),  # VERT02down
        storyboard.Do(storyboard.Activity.LIGHT_BACK,
                      intensity=1.0, fade=0.5),
        storyboard.Do(storyboard.Activity.LIGHT_LAYER,
                      intensity=0.0, fade=0.5),
        storyboard.Do(storyboard.Activity.PLAY_SOUND,
                      sound=fs_names.StoryFile('IC-SIBI-05')),
        # storyboard.Do(storyboard.Activity.ADVANCE_UP),  # VERT03
        storyboard.Do(storyboard.Activity.PLAY_SOUND,
                      sound=fs_names.StoryFile('IC-SIBI-06')),
        storyboard.Do(storyboard.Activity.LIGHT_BACK,
                      intensity=0.0, fade=1.0),
        storyboard.Do(storyboard.Activity.PLAY_SOUND,
                      sound=fs_names.StoryFile('IC-SIBI-07')),
        storyboard.Do(storyboard.Activity.WAIT_FOR_INPUT),
        # storyboard.Do(storyboard.Activity.ADVANCE_UP),  # VERT04
        storyboard.Do(storyboard.Activity.LIGHT_LAYER,
                      intensity=1.0, fade=1.0),
    ),
    storyboard.Chapter(
        storyboard.Do(storyboard.Activity.PLAY_SOUND,
                      sound=fs_names.StoryFile('IC-SIBI-08')),
        # storyboard.Do(storyboard.Activity.ADVANCE_LEFT), # HOR02
        storyboard.Do(storyboard.Activity.LIGHT_BACK,
                      intensity=1.0, fade=0.5),
        storyboard.Do(storyboard.Activity.LIGHT_LAYER,
                      intensity=0., fade=0.5),
        storyboard.Do(storyboard.Activity.PLAY_SOUND,
                      sound=fs_names.StoryFile('IC-SIBI-09')),
        storyboard.Do(storyboard.Activity.PLAY_SOUND,
                      sound=fs_names.SFX_REC_AUDIO),
        storyboard.Do(storyboard.Activity.PLAY_SOUND,
                      sound=fs_names.StoryFile('IC-SIBI-10')),
        storyboard.Do(storyboard.Activity.PLAY_SOUND,
                      sound=fs_names.StoryFile('IC-SIBI-11')),
        storyboard.Do(storyboard.Activity.LIGHT_BACK,
                      intensity=0., fade=1.0),
        storyboard.Do(storyboard.Activity.WAIT_FOR_INPUT),
        storyboard.Do(storyboard.Activity.PLAY_SOUND,
                      sound=fs_names.SFX_REC_AUDIO),
        storyboard.Do(storyboard.Activity.RECORD_SOUND,
                      filename=fs_names.REC_NAME,
                      duration=5.0,
                      cache=True),
        storyboard.Do(storyboard.Activity.PLAY_SOUND,
                      sound=fs_names.SFX_STOP_REC),
    ),
    storyboard.Chapter(
        storyboard.Do(storyboard.Activity.PLAY_SOUND,
                      sound=fs_names.StoryFile('IC-SIBI-12')),
        storyboard.Do(storyboard.Activity.PLAY_SOUND,
                      sound=fs_names.REC_NAME),
        storyboard.Do(storyboard.Activity.PLAY_SOUND,
                      sound=fs_names.StoryFile('IC-SIBI-13')),
        # storyboard.Do(storyboard.Activity.ADVANCE_UP),  # VERT05
        storyboard.Do(storyboard.Activity.LIGHT_LAYER,
                      intensity=1.0, fade=1.0),
        storyboard.Do(storyboard.Activity.PLAY_SOUND,
                      sound=fs_names.StoryFile('IC-SIBI-14')),
        # storyboard.Do(storyboard.Activity.ADVANCE_LEFT),  # HOR03
        storyboard.Do(storyboard.Activity.LIGHT_BACK,
                      intensity=1.0, fade=0.5),
        storyboard.Do(storyboard.Activity.LIGHT_LAYER,
                      intensity=0., fade=0.5),
        storyboard.Do(storyboard.Activity.PLAY_SOUND,
                      sound=fs_names.StoryFile('IC-SIBI-15')),
        storyboard.Do(storyboard.Activity.LIGHT_BACK,
                      intensity=0., fade=1.0),
        storyboard.Do(storyboard.Activity.PLAY_SOUND,
                      sound=fs_names.StoryFile('IC-SIBI-16')),
        storyboard.Do(storyboard.Activity.WAIT_FOR_INPUT)
    ),
    storyboard.Chapter(
        storyboard.Do(storyboard.Activity.PLAY_SOUND,
                      sound=fs_names.StoryFile('IC-SIBI-17')),
        storyboard.Do(storyboard.Activity.LIGHT_LAYER,
                      intensity=1.0, fade=1.0),
        storyboard.Do(storyboard.Activity.PLAY_SOUND,
                      sound=fs_names.StoryFile('IC-SIBI-18')),
        storyboard.Do(storyboard.Activity.LIGHT_LAYER,
                      intensity=0.0, fade=1.0),
        storyboard.Do(storyboard.Activity.PLAY_SOUND,
                      sound=fs_names.StoryFile('IC-SIBI-19')),
        storyboard.Do(storyboard.Activity.WAIT_FOR_INPUT),
    ),
    storyboard.Chapter(
        storyboard.Do(storyboard.Activity.PLAY_SOUND,
                      sound=fs_names.StoryFile('IC-SIBI-20')),
        storyboard.Do(storyboard.Activity.LIGHT_LAYER,
                      intensity=1.0, fade=1.0),
        storyboard.Do(storyboard.Activity.PLAY_SOUND,
                      sound=fs_names.StoryFile('IC-SIBI-21')),
        storyboard.Do(storyboard.Activity.LIGHT_LAYER,
                      intensity=0.0, fade=1.0),
        storyboard.Do(storyboard.Activity.PLAY_SOUND,
                      sound=fs_names.StoryFile('IC-SIBI-22')),
        storyboard.Do(storyboard.Activity.WAIT_FOR_INPUT),
    ),
    storyboard.Chapter(
        storyboard.Do(storyboard.Activity.PLAY_SOUND,
                      sound=fs_names.StoryFile('IC-SIBI-23')),
        storyboard.Do(storyboard.Activity.LIGHT_LAYER,
                      intensity=1.0, fade=1.0),
        storyboard.Do(storyboard.Activity.PLAY_SOUND,
                      sound=fs_names.StoryFile('IC-SIBI-24')),
        storyboard.Do(storyboard.Activity.LIGHT_LAYER,
                      intensity=0.0, fade=1.0),
        storyboard.Do(storyboard.Activity.PLAY_SOUND,
                      sound=fs_names.StoryFile('IC-SIBI-25')),
        storyboard.Do(storyboard.Activity.WAIT_FOR_INPUT),
        storyboard.Do(storyboard.Activity.LIGHT_LAYER,
                      intensity=1.0, fade=1.0),
    ),
    storyboard.Chapter(
        storyboard.Do(storyboard.Activity.PLAY_SOUND,
                      sound=fs_names.StoryFile('IC-SIBI-26')),
        storyboard.Do(storyboard.Activity.PLAY_SOUND,
                      sound=fs_names.StoryFile('IC-SIBI-27')),
        storyboard.Do(storyboard.Activity.WAIT_FOR_INPUT),
        storyboard.Do(storyboard.Activity.PLAY_SOUND,
                      sound=fs_names.SFX_REC_AUDIO),
        storyboard.Do(storyboard.Activity.RECORD_SOUND,
                      filename=fs_names.REC_CITY_NAME,
                      duration=5.0,
                      cache=False),
        storyboard.Do(storyboard.Activity.PLAY_SOUND,
                      sound=fs_names.SFX_STOP_REC),
        storyboard.Do(storyboard.Activity.LIGHT_LAYER,
                      intensity=0.0, fade=0.5),
        storyboard.Do(storyboard.Activity.LIGHT_BACK,
                      intensity=1.0, fade=0.5),
    ),
    storyboard.Chapter(
        storyboard.Do(storyboard.Activity.PLAY_SOUND,
                      sound=fs_names.StoryFile('IC-SIBI-28')),
        storyboard.Do(storyboard.Activity.PLAY_SOUND,
                      sound=fs_names.StoryFile('IC-SIBI-29')),
        storyboard.Do(storyboard.Activity.WAIT_FOR_INPUT),
        storyboard.Do(storyboard.Activity.PLAY_SOUND,
                      sound=fs_names.SFX_REC_AUDIO),
        storyboard.Do(storyboard.Activity.RECORD_SOUND,
                      filename=fs_names.REC_CITY_DESC,
                      duration=60.0,
                      cache=False),
        storyboard.Do(storyboard.Activity.PLAY_SOUND,
                      sound=fs_names.SFX_STOP_REC),
    ),
    storyboard.Chapter(
        storyboard.Do(storyboard.Activity.PLAY_SOUND,
                      sound=fs_names.StoryFile('IC-SIBI-30')),
        storyboard.Do(storyboard.Activity.PLAY_SOUND,
                      sound=fs_names.StoryFile('IC-SIBI-31')),
        storyboard.Do(storyboard.Activity.WAIT_FOR_INPUT),
        storyboard.Do(storyboard.Activity.PLAY_SOUND,
                      sound=fs_names.SFX_REC_AUDIO),
        storyboard.Do(storyboard.Activity.RECORD_SOUND,
                      filename=fs_names.REC_CITY_SOUND,
                      duration=60.0,
                      cache=False),
        storyboard.Do(storyboard.Activity.PLAY_SOUND,
                      sound=fs_names.SFX_STOP_REC),
    ),
    storyboard.Chapter(
        storyboard.Do(storyboard.Activity.PLAY_SOUND,
                      sound=fs_names.StoryFile('IC-SIBI-32')),
        storyboard.Do(storyboard.Activity.PLAY_SOUND,
                      sound=fs_names.StoryFile('IC-SIBI-33')),
        storyboard.Do(storyboard.Activity.PLAY_SOUND,
                      sound=fs_names.StoryFile('IC-SIBI-34')),
        storyboard.Do(storyboard.Activity.LIGHT_BACK,
                      intensity=0.0, fade=1.0),
        storyboard.Do(storyboard.Activity.WAIT_FOR_INPUT),
        storyboard.Do(storyboard.Activity.PLAY_SOUND,
                      sound=fs_names.SFX_REC_AUDIO),
        storyboard.Do(storyboard.Activity.RECORD_VIDEO,
                      filename=fs_names.REC_DRAW_CITY,
                      duration=70.0),
        storyboard.Do(storyboard.Activity.PLAY_SOUND,
                      sound=fs_names.SFX_STOP_REC),
    ),
    storyboard.Chapter(
        storyboard.Do(storyboard.Activity.LIGHT_BACK,
                      intensity=1.0, fade=1.0),
        storyboard.Do(storyboard.Activity.PLAY_SOUND,
                      sound=fs_names.StoryFile('IC-SIBI-35')),
        storyboard.Do(storyboard.Activity.PLAY_SOUND,
                      sound=fs_names.REC_NAME),
        storyboard.Do(storyboard.Activity.PLAY_SOUND,
                      sound=fs_names.StoryFile('IC-SIBI-36')),
        storyboard.Do(storyboard.Activity.LIGHT_BACK,
                      intensity=0.0, fade=2.0)
    )
]
